chartjs/Lab10/Models/ErrorViewModel.cs
namespace Lab10.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

chartjs/Lab10/Controllers/ChartJSController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;
using DataChartSources;
using Chart.Mvc.ComplexChart;


namespace Lab10.Controllers
{
    public class ChartJSController : Controller
    {
        public Random random;

        public ChartJSController()
        {
            random = new Random();
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Funkcja1()
        {
            DataChartSource1 source = new DataChartSource1(-5,5,1000);
            ViewBag.SourceX = JsonConvert.SerializeObject(source.GetX());
            ViewBag.SourceY = JsonConvert.SerializeObject(source.GetY());
            ViewBag.SourceLabels = JsonConvert.SerializeObject(source.GetXSF());
            return View();
        }
        public IActionResult Funkcja2()
        {
            DataChartSource2 source = new DataChartSource2(-5, 5, 1000);
            ViewBag.SourceX = JsonConvert.SerializeObject(source.GetX());
            ViewBag.SourceY = JsonConvert.SerializeObject(source.GetY());
            ViewBag.SourceLabels = JsonConvert.SerializeObject(source.GetXSF());
            return View();
        }
        public IActionResult BarChart() {

            return View();
        }
        public IActionResult PieChart() {
            return View();
        }
        public IActionResult MixedChart() {
            return View();
        }
        public IActionResult ChartMVCBarChart() {
            var barChart = new BarChart();
            barChart.ComplexData.Labels.AddRange(new List<string>() { "dane1", "dane2", "dane3", "dane4", "dane5" });
            barChart.ComplexData.Datasets.AddRange(new List<ComplexDataset>
                {new ComplexDataset
                    {
                    Data = [4,3,2,5,5],
                    Label = "set1",
                    FillColor = "rgba(220,220,220,0.2)",
                    StrokeColor = "rgba(220,220,220,1)",
                    PointColor = "rgba(220,220,220,1)",
                    PointStrokeColor = "#fff",
                    PointHighlightFill = "#fff",
                    PointHighlightStroke = "rgba(220,220,220,1)",
                    },
                new ComplexDataset
                    {
                    Data = [3,3,4,4,5],
                    Label = "set2",
                    FillColor = "rgba(151,187,205,0.2)",
                    StrokeColor = "rgba(151,187,205,1)",
                    PointColor = "rgba(151,187,205,1)",
                    PointStrokeColor = "#fff",
                    PointHighlightFill = "#fff",
                    PointHighlightStroke = "rgba(151,187,205,1)",
                    }
                });
            ViewBag.Chart = barChart;
            return View();
        }
        public IActionResult ChartMVCPieChart() {
            return View();
        }
    }
}

chartjs/Lab10/Controllers/HomeController.cs
using Lab10.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab10.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

chartjs/Lab10/Views/ChartJS/BarChart.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "Bar Chart";
}

<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        
    </style>
</head>
<body>
    <h1>Wykres słupkowy</h1>
    <div id="chartDiv">
        <canvas id="myChart"></canvas>
    </div>
    <script>
        const DATA_COUNT = 5;
        const NUMBER_CFG = { count: DATA_COUNT, min: -100, max: 100 };

        const labels = ['dane1','dane2','dane3','dane4','dane5'];
        const data = {
            labels: labels,
            datasets: [
                {
                    label: 'Seria 1',
                    data: [94,32,-4,-25,26],
                    borderColor: '#d92c16',
                    backgroundColor: '#d92c16',
                },
                {
                    label: 'Seria 2',
                    data: [22,33,-44,55,90],
                    borderColor: '#2dcf15',
                    backgroundColor: '#2dcf15',
                },
                {
                    label: 'Seria 3',
                    data: [-20,20,90,1,3],
                    borderColor: '#1528cf',
                    backgroundColor: '#1528cf'
                }
            ]
        };

        const config = {
            type: 'bar',
            data: data,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                        text: 'Chart.js Bar Chart'
                    }
                }
            },
        };

        new Chart(document.getElementById('myChart'), config, data);
    </script>
</body>

chartjs/Lab10/Views/ChartJS/ChartMVCBarChart.cshtml
@using Chart.Mvc.Extensions;
@using Chart.Mvc.ComplexChart;
@using Chart.Mvc.SimpleChart;
@using Chart.Mvc;
﻿@using System.Collections.Generic;
@using System.Web.Mvc;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "Bar Chart";
}

<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>

    </style>
</head>
<body>
    <h1>Wykres słupkowy</h1>
    <div id="chartDiv">
        <canvas id="myChart"></canvas>

        @*Html.CreateChart("myChart", ViewBag.Chart)*@
    </div>
</body>

chartjs/Lab10/Views/ChartJS/ChartMVCPieChart.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

chartjs/Lab10/Views/ChartJS/Funkcja1.cshtml
@{
    ViewData["Title"] = "Funkcja1";
}

<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        #chartDiv {
            width: 800px;
            height: 400px;
            border: solid 1px;
            padding: 1px;
            margin: 10px;
        }
    </style>
</head>
<body>
    <h1>Funkcja1</h1>
    <div id="chartDiv">
        <canvas id="myChart"></canvas>
    </div>
    <script>
        var x = (@Html.Raw(ViewBag.SourceX));
        var y = (@Html.Raw(ViewBag.SourceY));

        const labels = x.map(x => x.toFixed(2));
        const data = {
            labels: labels,
            datasets: [{
                label: 'Funkcja 1',
                data: y,
                fill: false,
                borderColor: 'rgb(75, 192, 192)',
                tension: 0.1
            }]
        };

        const config = {
            type: 'line',
            data: data,
        };

        new Chart(document.getElementById('myChart'), config, data);
    </script>
</body>

chartjs/Lab10/Views/ChartJS/Funkcja2.cshtml
@{
    ViewData["Title"] = "Funkcja2";
}

<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<style>
        #chartDiv {
            width: 800px;
            height: 400px;
            border: solid 1px;
            padding: 1px;
            margin: 10px;
        }
</style>
</head>
<body>
    <h1>Funkcja2</h1>
    <div id="chartDiv">
        <canvas id="myChart"></canvas>
    </div>
    <script>
        var x = (@Html.Raw(ViewBag.SourceX));
        var y = (@Html.Raw(ViewBag.SourceY));

        const labels = x.map(x => x.toFixed(2));
        const data = {
            labels: labels,
            datasets: [{
                label: 'Funkcja 1',
                data: y,
                fill: false,
                borderColor: 'rgb(75, 192, 192)',
                tension: 0.1
            }]
        };

        const config = {
            type: 'line',
            data: data,
        };

        new Chart(document.getElementById('myChart'), config, data);
    </script>
</body>

chartjs/Lab10/Views/ChartJS/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<h1><a asp-controller="ChartJS" asp-action="Funkcja1">Wykres funkcji 1</a></h1>
<h1><a asp-controller="ChartJS" asp-action="Funkcja2">Wykres funkcji 2</a></h1>
<h1><a asp-controller="ChartJS" asp-action="BarChart">Wykres słupkowy</a></h1>
<h1><a asp-controller="ChartJS" asp-action="PieChart">Wykres kołowy</a></h1>
<h1><a asp-controller="ChartJS" asp-action="MixedChart">Wykres kombinowany</a></h1>

chartjs/Lab10/Views/ChartJS/MixedChart.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "Mixed Chart";
}

<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>

    </style>
</head>
<body>
    <h1>Wykres kombinowany</h1>
    <div id="chartDiv">
        <canvas id="myChart"></canvas>
    </div>
    <script>
        const mixedChart = new Chart(document.getElementById('myChart'), {
            data: {
                datasets: [{
                    type: 'bar',
                    label: 'Bar Dataset',
                    data: [11, 22, 33, 44, 55]
                }, {
                    type: 'line',
                    label: 'Line Dataset',
                    data: [20, 70, -5, 30, 40],
                }],
                labels: ['January', 'February', 'March', 'April', 'May']
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });

    </script>
</body>

chartjs/Lab10/Views/ChartJS/PieChart.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "Pie Chart";
}

<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        #chartDiv {
            width: 500px;
            height: 600px;
            border: solid 1px;
            padding: 1px;
            margin: 10px;
        }
    </style>
</head>
<body>
    <h1>Wykres kołowy</h1>
    <div id="chartDiv">
        <canvas id="myChart"></canvas>
    </div>
    <script>
        const DATA_COUNT = 5;
        const NUMBER_CFG = { count: DATA_COUNT, min: 0, max: 100 };

        const data = {
            labels: ['Red', 'Orange', 'Yellow', 'Green', 'Blue'],
            datasets: [
                {
                    label: 'Dataset 1',
                    data: [10,33,20,15,22],
                    backgroundColor: ['#eb4034', '#e0850d', '#fffb00', '#05ff16', '#020ee6'],
                }
            ]
        };

        const config = {
            type: 'pie',
            data: data,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                        text: 'Chart.js Pie Chart'
                    }
                }
            },
        };

        new Chart(document.getElementById('myChart'), config, data);
    </script>
</body>
</html>

chartjs/Lab10/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a asp-action="Index" asp-controller="ChartJS">Wykresy</a>
</div>

chartjs/Lab10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab10</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab10.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab10</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lab10 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>